# Review Notebook: Python Basics & Pandas Fundamentals 

Pandas is a toolbox used for data manipulation

This notebook provides a comprehensive review of the material covered in the first two weeks of the course, including Jupyter notebook basics, Python syntax, and an introduction to data manipulation with pandas.

## 1. Jupyter Notebook Basics & Shortcuts

### REMEMBER THE ORDER YOU RUN THE NOTEBOOK IS IMPORTANT

<img src="screenshots/code_markdown_restart.png" />

### Essential Shortcuts

| Action | Mac Shortcut | Windows/Linux Shortcut |
| :--- | :--- | :--- |
| **Run cell & select next** | `Shift + Enter` | `Shift + Enter` |
| **Run selected cells** | `Option + Enter` | `Ctrl + Enter` |
| **Run cell & insert below** | `Cmd + Enter` | `Alt + Enter` |
| **Enter Command Mode** | `Esc` | `Esc` |
| **Enter Edit Mode** | `Enter` | `Enter` |
| **Insert cell above** (Command mode) | `A` | `A` |
| **Insert cell below** (Command mode) | `B` | `B` |
| **Change to Markdown** (Command mode) | `M` | `M` |
| **Change to Code** (Command mode) | `Y` | `Y` |
| **Delete selected cell** (Command mode) | `D, D` (Double tap) | `D, D` (Double tap) |
| **Save and Checkpoint** | `Cmd + S` | `Ctrl + S` |
| **Undo cell deletion** (Command mode) | `Z` | `Z` |

## 2. File Paths and Environment

Understanding where your data is located is crucial in Python. The `os` module allows you to interact with your operating system, including finding out what folder you are currently in.

In [ ]:
import os

# Check what folder this notebook is running in
print(f"Current working directory: {os.getcwd()}")

# List files in the current folder
print("\nFiles in current folder:")
print(os.listdir("."))

# List files in the folder two levels up (often where 'data' lives)
print(os.listdir("../"))

Current working directory: /Users/cory/Desktop/datascience-publicpolicy-2026/notebooks/week_3

Files in current folder:
['screenshots', 'review.ipynb']
['week_2', '.DS_Store', 'hw', 'week_3']

## 3. Python Fundamentals Review

Based on `2-python-fundamentals.ipynb`, here are the core concepts of Python grammar.

### 3.1 Variables and Assignment
Use `=` to save information into a variable name.

In [38]:
# Saving a string (Note: strings use quotes!)
course_name = "Data Science for Public Policy"


MYINFORMATION = "THIS INFORMATION IS COOL"

# Saving a number (int or float)
year = 2026
gpa_requirement = 3.5

countries = ["US", "JP", "CN"]

countires_map = {"US": "United States", "JP": "JAPAN!!"}

# Checking types
print(type(course_name))
print(type(year))

<class 'str'>
<class 'int'>

### 3.2 Dictionaries
Dictionaries are key-value pairs using curly braces `{}`.

In [44]:
# Example of a Dictionary for renaming columns or mapping data
rename_country_map = {
    "USA": "United States",
    "CAN": "Canada",
    "MEX": "Mexico",
    "JPN": "Japan"
}

print("Keys:", rename_country_map.keys())
print("Values:", rename_country_map.values())

Keys: dict_keys(['USA', 'CAN', 'MEX', 'JPN'])
Values: dict_values(['United States', 'Canada', 'Mexico', 'Japan'])

## 4. Pandas for Data Manipulation

Pandas is the primary library for working with tabular data (DataFrames).

### 4.1.A Try to understand why there is an error

In [4]:
path = "../../data/hw/democracy_gdp.csv"
df = pd.read_csv(path)
df.head(2)

NameError: name 'pd' is not defined

### 4.1 Loading Data & Exploration
You can load data from local files or directly from a URL (e.g., GitHub).

In [2]:
import pandas as pd

# Loading from a URL directly
url = "https://raw.githubusercontent.com/corybaird/datascience-publicpolicy-2026/refs/heads/main/data/examples/week_2/world_bank_data.csv"
df = pd.read_csv(url)
#df = 'Cory'
# THIS TEXT IS ignored
# Quick look at the top rows
df.head(3)

,Unnamed: 0,indicator,country,countryiso3code,date,value
0,0,GDP per capita (current US$),Canada,CAN,2023,53431.185706
1,1,GDP per capita (current US$),Canada,CAN,2022,55509.393176
2,2,GDP per capita (current US$),Canada,CAN,2021,52496.844169

In [3]:
# Getting information about the columns, data types, and missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       12 non-null     int64
 1   indicator        12 non-null     object
 2   country          12 non-null     object
 3   countryiso3code  12 non-null     object
 4   date             12 non-null     int64
 5   value            12 non-null     float64
dtypes: float64(1), int64(2), object(3)
memory usage: 708.0+ bytes

In [4]:
# Viewing the bottom rows
df.tail(2)

,Unnamed: 0,indicator,country,countryiso3code,date,value
10,10,GDP per capita (current US$),United States,USA,2022,78035.175360
11,11,GDP per capita (current US$),United States,USA,2021,71318.307359

In [5]:
# Seeing all unique values in a specific column
df.country.unique()

array(['Canada', 'Japan', 'Mexico', 'United States'], dtype=object)

In [6]:
df.country.unique()

array(['Canada', 'Japan', 'Mexico', 'United States'], dtype=object)

### 4.2 Selecting and Filtering
Filtering rows based on conditions is identical to creating a 'subset' in other software.

In [7]:
# 1. Selecting a single column
mydataset = df[['country', 'date', 'value']]
mydataset

          country  date         value
0          Canada  2023  53431.185706
1          Canada  2022  55509.393176
2          Canada  2021  52496.844169
3           Japan  2023  33766.526825
4           Japan  2022  34017.271808
5           Japan  2021  40058.537328
6          Mexico  2023  13790.024343
7          Mexico  2022  11385.407076
8          Mexico  2021  10314.050674
9   United States  2023  82769.412211
10  United States  2022  78035.175360
11  United States  2021  71318.307359

In [10]:
# 2. Filtering with .query()
df.query("country == 'Japan'    ")

,Unnamed: 0,indicator,country,countryiso3code,date,value
3,3,GDP per capita (current US$),Japan,JPN,2023,33766.526825
4,4,GDP per capita (current US$),Japan,JPN,2022,34017.271808
5,5,GDP per capita (current US$),Japan,JPN,2021,40058.537328

In [12]:
# 3. Filtering with Boolean Masks (Alternative to .query)
mask = df.country == 'Japan'
df[mask]

,Unnamed: 0,indicator,country,countryiso3code,date,value
3,3,GDP per capita (current US$),Japan,JPN,2023,33766.526825
4,4,GDP per capita (current US$),Japan,JPN,2022,34017.271808
5,5,GDP per capita (current US$),Japan,JPN,2021,40058.537328

In [13]:
# 4. Multiple Conditions in .query()
# Remember the ampersand (&) means AND, pipe (|) means OR
df.query("country == 'Japan' & date > 2021")

,Unnamed: 0,indicator,country,countryiso3code,date,value
3,3,GDP per capita (current US$),Japan,JPN,2023,33766.526825
4,4,GDP per capita (current US$),Japan,JPN,2022,34017.271808

In [14]:
df.query("country == 'Japan' | date > 2021")

,Unnamed: 0,indicator,country,countryiso3code,date,value
0,0,GDP per capita (current US$),Canada,CAN,2023,53431.185706
1,1,GDP per capita (current US$),Canada,CAN,2022,55509.393176
3,3,GDP per capita (current US$),Japan,JPN,2023,33766.526825
4,4,GDP per capita (current US$),Japan,JPN,2022,34017.271808
5,5,GDP per capita (current US$),Japan,JPN,2021,40058.537328
6,6,GDP per capita (current US$),Mexico,MEX,2023,13790.024343
7,7,GDP per capita (current US$),Mexico,MEX,2022,11385.407076
9,9,GDP per capita (current US$),United States,USA,2023,82769.412211
10,10,GDP per capita (current US$),United States,USA,2022,78035.175360

## 5. Homework 1 Highlights

In homework 1, we practiced downloading data directly from an API using the `requests` library.

### 5.A.1 YOU CREATE: Tool/Function

In [15]:
def add_func(a,b,c):
    #print('This function adds')
    final = a+b+c
    return final

In [16]:
add_func(
    1,2,3
)

6

In [21]:
def build_yourown(piece_1 =1, piece_2 =2):
    #print(piece_1, piece_2)
    add = piece_1 + piece_2
    add = piece_1 + piece_2
    add = piece_1 + piece_2
    return add

build_yourown(
    piece_1=2,
    piece_2=3
)

5

### 5.A.2 SOMONE ELSE CREATES: Tool/Functions

In [ ]:
import os
os.listdir()
os.getcwd()
import pandas as pd

In [ ]:
# pd.read_csv("")
# pd.read_excel("")
# pd.merge()

### 5.1.1 Download

In [38]:
import requests
import io

def download_worldbank(indicator, countries, date_start, date_end):
    """
    A helper function to download data from the World Bank API.
    """
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    
    # Reading the XML response into pandas
    df = pd.read_xml(io.BytesIO(response.content))
    return df

In [39]:
# Test downloading GDP Data using HW1 example list
hw_country_list = ["USA", "CAN", "MEX", "GBR", "FRA", "DEU", "JPN", "AUS"]
gdp_indicator = 'NY.GDP.PCAP.CD'

gdp_api_data = download_worldbank(
    indicator=gdp_indicator,
    date_start=1990,
    date_end=2026,
    countries=hw_country_list,
)

gdp_api_data.head()

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),Australia,AUS,2025,NaN,NaN,NaN,1
1,GDP per capita (current US$),Australia,AUS,2024,64603.985631,NaN,NaN,1
2,GDP per capita (current US$),Australia,AUS,2023,65058.377315,NaN,NaN,1
3,GDP per capita (current US$),Australia,AUS,2022,65169.519112,NaN,NaN,1
4,GDP per capita (current US$),Australia,AUS,2021,60758.904440,NaN,NaN,1

### 5.1.2 Select columns

In [ ]:
short_data = gdp_api_data.query("date > 2021 &")[['country', 'date', 'value']]
short_data.head(3)

     country  date         value
0  Australia  2025           NaN
1  Australia  2024  64603.985631
2  Australia  2023  65058.377315